config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/", :controller => "todolists", :action => "index"
  get "/login", :controller => "sessions", :action => "new"
  get "/logout", :controller => "sessions", :action => "destroy"
  get "todos/:id/edit", to: "todos#edit", as: "edit_todo"
  patch "todos/:id", to: "todos#update", as: "update_todo"
  get "todolists/:id/edit", to: "todolists#edit", as: "edit_todolist"
  get "/delete", :controller => "todolists", :action => "destroy"
  patch "todos/:id/update", to: "todos#update_status", as: "update_status_todo"
  get "/delete", :controller => "todos", :action => "destroy"
  get "usergroups/:id/edit", to: "usergroups#edit", as: "edit_usergroup"
  get "/delete", :controller => "usergroups", :action => "destroy"
  post "/usergroupusers/new.:id", to: "usergroupusers#new", as: "new_usergroupuser_path"

  resources "todos"
  resources "todolists"
  resources "sessions"
  resources "users"
  resources "usergroups"
  resources "usergroupusers"
end

app/models/usergroup.rb
class Usergroup < ApplicationRecord
end

app/controllers/usergroups_controller.rb
class UsergroupsController < ApplicationController
    def index
        if @current_user
            @usergroups = Usergroup.where({ 
                "owning_user_id" => @current_user["id"]
              })
        else
            flash["notice"] = "Login first."
            redirect_to "/login"
        end
    end

    def new
        @usergroup = Usergroup.new
        @usergroupuser = Usergroupuser.new
    end
    
    def create
        @usergroup = Usergroup.new
        @usergroup["name"] = params["usergroup"]["name"]
        @usergroup["owning_user_id"] = @current_user["id"]          
        @usergroup.save
        @usergroupuser = Usergroupuser.new
        @usergroupuser["usergroup_id"] = @usergroup["id"]
        @usergroupuser["user_id"] = @current_user["id"]
        @usergroupuser.save 
        redirect_to "/usergroups"
    end

    def destroy
        if @current_user
            @usergroup = Usergroup.find_by({ "owning_user_id" => @current_user["id"] })
            @usergroupusers = Usergroupuser.find_by({ "usergroup_id" => @usergroup["id"] })
            @usergroupusers.destroy
            @usergroup.destroy
            flash["notice"] = "User group successfully deleted."
            redirect_to "/usergroups"
        else
            flash["notice"] = "Login first."
            redirect_to "/login"
        end
    end

end

app/views/usergroups/edit.html.erb
<% @users_all = User.all %>
<% @usergroup = Usergroup.find_by({ "id" => params["id"] }) %>
<% @usergroupusers = Usergroupuser.where({ "usergroup_id" => @usergroup["id"] })  %>

<h3>Edit User Group <%= @usergroup["name"] %></h3>

<h4>Users currently assigned</h4>
<table class="table">
    <tr>
        <th>User</th>
        <th>Action</th>
    </tr>
    <% for usergroupuser in @usergroupusers %>
    <tr>
        <% @user = User.find_by({ "id" => usergroupuser["user_id"] }) %>
        <% user_owning = @usergroup["owning_user_id"] ==  @user["id"] %>
        <% if user_owning %>
            <td><%= @user["first_name"] %> (Owning User)</td>
            <td>
            </td>
        <% else %>
            <td><%= @user["first_name"] %></td>
            <td>
                <%= button_to "Delete", usergroupuser_path(usergroupuser), method: :delete, class: "btn btn-danger btn-sm" %>
            </td>
        <% end %>
    </tr> 
    <% end %>
</table>

<h4>Users currently not assigned</h4>
<table class="table">
    <tr>
        <th>User</th>
        <th>Action</th>
    </tr>
    <% for user in @users_all %>
        <% user_check = Usergroupuser.where({ "usergroup_id" => @usergroup["id"], "user_id" => user }).empty? %>
        <% if user_check %>
            <tr>
                <td><%= user["first_name"] %></td>
                <td><%= button_to "Add", new_usergroupuser_path(usergroupuser, :usergroup_id => @usergroup["id"], :user_id => user["id"]), method: :post, class: "btn btn-success btn-sm" %></td>
            </tr>
        <% end %> 
    <% end %> 
</table>



    
 

app/views/usergroups/index.html.erb
<h3>User Groups</h3>

<div class="col text-right">
    <a href="/usergroups/new/" class="btn btn-secondary btn-sm">New User Group</a>
</div>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Owning User</th>
        <th>Actions</th>
    </tr>
    <% for usergroup in @usergroups %>
        <tr>
            <td><%= usergroup["name"] %></td>
            <% user = User.find_by({ "id" => usergroup["owning_user_id"] }) %>
            <td><%= user["first_name"] %></td>
            <td>
            <table>
                <tr>
                    <td>
                        <%= button_to "Delete", usergroup_path(usergroup), method: :delete, class: "btn btn-danger btn-sm" %>
                    </td>
                    <td>
                        <%= button_to "Show", edit_usergroup_path(usergroup), method: :get, class: "btn btn-success btn-sm" %>
                    </td>
                 </tr>   
            </table>
            </td>
        </tr>
    <% end %>
</table>

app/views/usergroups/new.html.erb
<h3>Create Usergroup</h3>

<%= form_with :model => @usergroup do |form| %>
  <div class="mb-3">
    <%= form.label "name", :class => "form-label" %>
    <%= form.text_field "name", :class => "form-control" %>
  </div>

  <%= form.submit "Create", :class => "btn btn-primary" %>
<% end %>