config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/", :controller => "todolists", :action => "index"
  get "/login", :controller => "sessions", :action => "new"
  get "/logout", :controller => "sessions", :action => "destroy"
  get "todos/:id/edit", to: "todos#edit", as: "edit_todo"
  patch "todos/:id", to: "todos#update", as: "update_todo"
  get "todolists/:id/edit", to: "todolists#edit", as: "edit_todolist"
  get "/delete", :controller => "todolists", :action => "destroy"
  patch "todos/:id/update", to: "todos#update_status", as: "update_status_todo"
  get "/delete", :controller => "todos", :action => "destroy"
  get "usergroups/:id/edit", to: "usergroups#edit", as: "edit_usergroup"
  get "/delete", :controller => "usergroups", :action => "destroy"
  post "/usergroupusers/new.:id", to: "usergroupusers#new", as: "new_usergroupuser_path"

  resources "todos"
  resources "todolists"
  resources "sessions"
  resources "users"
  resources "usergroups"
  resources "usergroupusers"
end

app/models/todolist.rb
class Todolist < ApplicationRecord
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController

    def index
        if @current_user
            @todolists = Todolist.where({ 
                "user_id" => @current_user["id"]
              })
        else
            flash["notice"] = "Login first."
            redirect_to "/login"
        end
    end

    def new
        if @current_user
            @todolist = Todolist.new
        else
            flash["notice"] = "Login first."
            redirect_to "/login"
        end
    end

    def create
        if @current_user
            @todolist = Todolist.new
            @todolist["title"] = params["todolist"]["title"]
            @todolist["user_id"] = @current_user["id"]
            @todolist.save
            flash["notice"] = "To-do list created successfully."
            redirect_to "/todolists"
        else
            flash["notice"] = "Login first."
            redirect_to "/login"
        end
    end

    def edit
        if @current_user
            @todolist = Todolist.find_by({ "id" => params["id"] })
            render :edit
        else
            flash["notice"] = "Login first."
            redirect_to "/login"
        end
    end
    
    def update
        @todolist = Todolist.find(params[:id])
        if @todolist.update(params.require(:todolist).permit(:title))
            flash["notice"] = "To-do List successfully updated."
            redirect_to "/todolists"
        else
            flash["notice"] = "To-do List update failed."
            render :edit
        end
    end

    def destroy
        if @current_user
            @todolist = Todolist.find_by({ "id" => params["id"] })
            @todos = Todo.where({ 
                "todolist_id" => @todolist["id"]
              })
            for todo in @todos
                todo.destroy
            end
            @todolist.destroy
            flash["notice"] = "To-do list successfully deleted."
            redirect_to "/todolists"
        else
            flash["notice"] = "Login first."
            redirect_to "/login"
        end
    end

end

app/views/todolists/edit.html.erb
<h4>Edit To-Do List "<%= @todolist["title"] =%>"</h4>

<% if @current_user %>
    <%= form_with :model => @todolist do |form| %>
        <div class="mb-3">
            <%= form.label "title", :class => "form-label" %>
            <%= form.text_field "title", :class => "form-control" %>
        </div>

    <%= form.submit "Save To-Do List", :class => "btn btn-primary" %>
<% end %>
<% else %>
    You must first <a href="/login">login</a> to create a To-Do.
<% end %>

app/views/todolists/index.html.erb
<h3>To-Do Lists</h3>

<div class="col text-right">
    <a href="/todolists/new/" class="btn btn-secondary btn-sm">New To-Do List</a>
</div>

<table class="table">
    <tr>
        <th>Title</th>
        <th>User</th>
        <th>Actions</th>
    </tr>
    <% for todolist in @todolists %>
        <tr>
            <td><a href="/todos?todolist_id=<%= todolist["id"] %>" class="link-dark"><%= todolist["title"] %></a></td>
            <% user = User.find_by({ "id" => @current_user["id"] }) %>
            <td><%= user["first_name"] %></td>
            <td>
            <table>
                <tr>
                    <td>
                        <%= button_to "Delete", todolist_path(todolist), method: :delete, class: "btn btn-danger btn-sm" %>
                    </td>
                    <td>
                        <%= button_to "Edit", edit_todolist_path(todolist), method: :get, class: "btn btn-warning btn-sm" %>
                    </td>
                 </tr>   
            </table>
            </td>
        </tr>
    <% end %>
</table>

app/views/todolists/new.html.erb
<h3>New To-Do List</h3>

<% if @current_user %>
    <%= form_with :model => @todolist do |form| %>
        <div class="mb-3">
        <%= form.label "title", :class => "form-label" %>
        <%= form.text_field "title", :class => "form-control" %>
        </div>

    <%= form.submit "Create To-Do List", :class => "btn btn-primary" %>
<% end %>
<% else %>
    You must first <a href="/login">login</a> to create a To-Do.
<% end %>