config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/", :controller => "todolists", :action => "index"
  get "/login", :controller => "sessions", :action => "new"
  get "/logout", :controller => "sessions", :action => "destroy"
  get "todos/:id/edit", to: "todos#edit", as: "edit_todo"
  patch "todos/:id", to: "todos#update", as: "update_todo"
  get "todolists/:id/edit", to: "todolists#edit", as: "edit_todolist"
  get "/delete", :controller => "todolists", :action => "destroy"
  patch "todos/:id/update", to: "todos#update_status", as: "update_status_todo"
  get "/delete", :controller => "todos", :action => "destroy"
  get "usergroups/:id/edit", to: "usergroups#edit", as: "edit_usergroup"
  get "/delete", :controller => "usergroups", :action => "destroy"
  post "/usergroupusers/new.:id", to: "usergroupusers#new", as: "new_usergroupuser_path"

  resources "todos"
  resources "todolists"
  resources "sessions"
  resources "users"
  resources "usergroups"
  resources "usergroupusers"
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    def index
        if @current_user
            @todos = Todo.where({ 
                "user_id" => @current_user["id"],
                "todolist_id" => params["todolist_id"]
              }).sort_by(&:duedate)
        else
            flash["notice"] = "Login first."
            redirect_to "/login"
        end
    end

    def new
        if @current_user
            @todo = Todo.new
        else
            flash["notice"] = "Login first."
            redirect_to "/login"
        end
    end

    def create
        if @current_user
            @todo = Todo.new
            @todo["description"] = params["todo"]["description"]
            @todo["duedate"] = params["todo"]["duedate"]
            @todo["done"] = false
            @todo["user_id"] = @current_user["id"]
            @todo["todolist_id"] = params["todo"]["todolist_id"]
            if @todo["duedate"] >= Time.new.strftime("%Y-%m-%d")
                @todo.save
                flash["notice"] = "To-do created successfully." 
                redirect_to "/todos?todolist_id="+@todo["todolist_id"].to_s
            else
                flash["notice"] = "Due date in the past" 
                redirect_to "/todos/new?todolist_id="+@todo["todolist_id"].to_s
            end
        else
            flash["notice"] = "Login first."
            redirect_to "/login"
        end
 
    end

    def edit
        if @current_user
            @todo = Todo.find_by({ "id" => params["id"] })
            if @todo["done"] == false
                render :edit
            else
                flash["notice"] = "Uncheck to-do before edit."
                redirect_to "/todos?todolist_id="+@todo["todolist_id"].to_s
            end
        else
            flash["notice"] = "Login first."
            redirect_to "/login"
        end
    end
    
    def update
        @todo = Todo.find(params[:id])
        if params["todo"]["duedate"] >= Time.new.strftime("%Y-%m-%d")
            if @todo.update(params.require(:todo).permit(:description, :duedate))
                flash["notice"] = "To-do successfully updated."
                redirect_to "/todos?todolist_id="+@todo["todolist_id"].to_s
            else
                flash["notice"] = "To-do update failed."
                render :edit
            end
        else
            flash["notice"] = "To-do update failed. Due date in the past." 
            redirect_to "/todos?todolist_id="+@todo["todolist_id"].to_s
        end
    end

    def update_status
        if @current_user
            @todo = Todo.find(params[:id])
            if @todo["done"] == false
                @todo["done"] = true
                flash["notice"] = "To-do successfully checked off."
            else
                @todo["done"] = false
                flash["notice"] = "To-do successfully unchecked."
            end
            @todo.save
            redirect_to "/todos?todolist_id="+@todo["todolist_id"].to_s
        else
            flash["notice"] = "Login first."
            redirect_to "/login"
        end
    end

    def destroy
        if @current_user
            @todo = Todo.find_by({ "id" => params["id"] })
            @todo.destroy
            flash["notice"] = "To-do successfully deleted."
            redirect_to "/todos?todolist_id="+@todo["todolist_id"].to_s
        else
            flash["notice"] = "Login first."
            redirect_to "/login"
        end
    end
end

app/views/todos/edit.html.erb
<h3>Edit To-Do "<%= @todo["description"] =%>"</h3>

<% if @current_user %>
    <%= form_with :model => @todo do |form| %>
        <div class="mb-3">
            <%= form.label "description", :class => "form-label" %>
            <%= form.text_field "description", :class => "form-control" %>
        </div>

        <div class="mb-3">
            <%= form.label "Due Date", :class => "form-label" %>
            <%= form.date_field "duedate", :class => "form-control" %>
        </div>

    <%= form.submit "Save To-Do", :class => "btn btn-primary" %>
<% end %>
<% else %>
    You must first <a href="/login">login</a> to create a To-Do.
<% end %>

app/views/todos/index.html.erb
<h3>To-Do List</h3>

<div class="col text-right">
  <a href="/todos/new?todolist_id=<%= params["todolist_id"] %>" class="btn btn-secondary btn-sm">New To-Do</a>
</div>

<table class="table">
  <tr>
    <th>Responsible</th>
    <th>To-Do</th>
    <th>Due date</th>
    <th>Done</th>
    <th>Actions</th>
  </tr>
  <% for todo in @todos %>
    <% if todo["done"] == false %>
      <tr>
        <td>
        <%# find user who created todo %>
        <% user = User.find_by({ "id" => todo["user_id"] }) %>
        <%# handle any potential bad data where the todo is missing a user %>
        <% if user %>
          <%= user["first_name"] %>
        <% else %>
          anonymous
        <% end %>
        </td>
        <td><%= todo["description"] %></td>
        <td>
          <% if Time.now > todo["duedate"] %>
            <div class="text-danger"><%= todo["duedate"].strftime("%m/%d/%Y") %></divp>
          <% else %>
            <%= todo["duedate"].strftime("%m/%d/%Y") %>
          <% end %>
        </td>
        <td>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-circle" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
          </svg>
        </td>
        <td>
          <table>
            <tr>
              <td>
                <%= button_to "Delete", todo_path(todo), method: :delete, class: "btn btn-danger btn-sm" %>
              </td>
              <td>
                <%= button_to "Edit", edit_todo_path(todo), method: :get, class: "btn btn-warning btn-sm" %>
              </td>
              <td>
                <%= button_to "Check", update_status_todo_path(todo), method: :patch, class: "btn btn-success btn-sm" %>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    <% end %>
  <% end %>
  <% for todo in @todos %>
    <% if todo["done"] == true %>
      <tr>
        <td>
        <%# find user who created post %>
        <% user = User.find_by({ "id" => todo["user_id"] }) %>
        <%# handle any potential bad data where the post is missing a user %>
        <% if user %>
          <%= user["first_name"] %>
        <% else %>
          anonymous
        <% end %>
        </td>
        <td><s><%= todo["description"] %></s></td>
        <td><s><%= todo["duedate"].strftime("%m/%d/%Y") %></s></td>
        <td>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-circle-fill" viewBox="0 0 16 16">
            <circle cx="8" cy="8" r="8"/>
          </svg>
        </td>
        <td>
          <table>
            <tr>
              <td>
                <%= button_to "Delete", todo_path(todo), method: :delete, class: "btn btn-danger btn-sm" %>
              </td>
              <td>
                <%= button_to "Edit", edit_todo_path(todo), method: :get, class: "btn btn-warning btn-sm" %>
              </td>
              <td>
                <%= button_to "Uncheck", update_status_todo_path(todo), method: :patch, class: "btn btn-success btn-sm" %>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/todos/new.html.erb
<h3>New To-Do</h3>

<% if @current_user %>
    <%= form_with :model => @todo do |form| %>
        <div class="mb-3">
        <%= form.label "description", :class => "form-label" %>
        <%= form.text_field "description", :class => "form-control" %>
        </div>

        <div class="mb-3">
        <%= form.label "Due Date", :class => "form-label" %>
        <%= form.date_field "duedate", :class => "form-control" %>
        </div>

        <%= form.hidden_field :todolist_id, :value => params["todolist_id"] %>

    <%= form.submit "Create To-Do", :class => "btn btn-primary" %>
<% end %>
<% else %>
    You must first <a href="/login">login</a> to create a To-Do.
<% end %>